### ISSUE TITLE
Invariant Violation: Expected targetIds to be registered.

### ISSUE THREAD

**Issue by alexeyvokin** [hcg1023/vue3-dnd#72]
I have issues similar to [763](https://github.com/react-dnd/react-dnd/issues/763) and [3403](https://github.com/react-dnd/react-dnd/issues/3403) in the current version of the package.

I investigated this issue and concluded that it is necessary to update the `dnd-core` package (as a dependency) to the latest version.

```
ERROR
Expected targetIds to be registered.
Invariant Violation: Expected targetIds to be registered.
    at invariant (webpack-internal:///./node_modules/@react-dnd/invariant/dist/esm/index.mjs:26:21)
    at checkInvariants (webpack-internal:///./node_modules/vue3-dnd/node_modules/dnd-core/dist/esm/actions/dragDrop/hover.mjs:40:72)
    at DragDropManagerImpl.hover (webpack-internal:///./node_modules/vue3-dnd/node_modules/dnd-core/dist/esm/actions/dragDrop/hover.mjs:17:9)
    at Object.eval [as hover] (webpack-internal:///./node_modules/vue3-dnd/node_modules/dnd-core/dist/esm/classes/DragDropManagerImpl.mjs:25:46)
    at eval (webpack-internal:///./node_modules/react-dnd-html5-backend/dist/esm/HTML5BackendImpl.mjs:316:38)
```

**Comment by hcg1023** [comment]
Ok thanks, I will update and post it within today

**Comment by alexeyvokin** [comment]
> Ok thanks, I will update and post it within today

thank you 🙏

**Comment by hcg1023** [comment]
@alexeyvokin 
Sorry, due to some errors in CI, the change was delayed until today. Please update to vue3-dnd@2.1.0

**Comment by alexeyvokin** [comment]
@hcg1023 thanks, it works as expected.
